# Mod Properties
mod_version=1.1.0
mod_id=ChainTogether
mod_group_id=com.evailcodes
mod_name=Chain Together NeoForge
mod_authors=EVAilCodes
mod_license=MIT
mod_description=A mod that chains players together!

# Minecraft Properties
minecraft_version=1.21.1
neo_version=21.0.103-beta
mapping_channel=official
mapping_version=1.21.1

# Mod Loader Properties
loader_version_range=[4,)
minecraft_version_range=[1.21.1,1.22)
neo_version_range=[21.0,)

# Project Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

org.gradle.jvmargs=-Dfile.encoding=UTF-8